language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-text tests

notifications:
    on_success: never
    on_failure: always
